// <auto-generated />
using System;
using APITestPyscoIA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APITestPyscoIA.Migrations
{
    [DbContext(typeof(DatosDbContext))]
    [Migration("20250825023622_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.CiudadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Ciudades");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionOpcionesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdConfiguracionBancoPreguntas")
                        .HasColumnType("int");

                    b.Property<string>("Opcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdConfiguracionBancoPreguntas");

                    b.ToTable("ConfiguracionesOpciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionPreguntasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfiguracionSeccionesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdConfiguracionSecciones")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionSeccionesId");

                    b.ToTable("ConfiguracionesPreguntas");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionSeccionesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfiguracionTestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("FormulaAgregado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdConfiguracionesTest")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoSecciones")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPreguntas")
                        .HasColumnType("int");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoSeccionesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionTestId");

                    b.HasIndex("TipoSeccionesId");

                    b.ToTable("ConfiguracionesSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("int");

                    b.Property<int>("IdEvaluador")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTest")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoExpiracion")
                        .HasColumnType("int");

                    b.Property<int>("TipoTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("TipoTestId");

                    b.ToTable("ConfiguracionesTest");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.EvaluadorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Evaluadores");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.PaisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ProvinciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("CantidadPreguntas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdConfiguracionTest")
                        .HasColumnType("int");

                    b.Property<int>("IdEvaluador")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConfiguracionTest");

                    b.HasIndex("IdEvaluador");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestPreguntasModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfiguracionBancoPreguntasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<int>("IdConfiguracionBancoPreguntas")
                        .HasColumnType("int");

                    b.Property<int>("IdTestSecciones")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestSeccionesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionBancoPreguntasId");

                    b.HasIndex("TestSeccionesId");

                    b.ToTable("TestsPreguntas");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestSeccionesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("CantidadPreguntas")
                        .HasColumnType("int");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<int>("ConfiguracionSeccionesId")
                        .HasColumnType("int");

                    b.Property<int>("Contestadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinTest")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioTest")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConfiguracionSecciones")
                        .HasColumnType("int");

                    b.Property<int>("IdTest")
                        .HasColumnType("int");

                    b.Property<bool>("Iniciado")
                        .HasColumnType("bit");

                    b.Property<int>("NoContestadas")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracionSeccionesId");

                    b.HasIndex("TestId");

                    b.ToTable("TestSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TipoSeccionesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoTest")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TipoTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoTestId");

                    b.ToTable("TipoSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TipoTestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Actualizado")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoTest");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.CiudadModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ProvinciaModel", "Provincia")
                        .WithMany("Ciudades")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionOpcionesModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionPreguntasModel", "ConfiguracionBancoPreguntas")
                        .WithMany("Opciones")
                        .HasForeignKey("IdConfiguracionBancoPreguntas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionBancoPreguntas");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionPreguntasModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionSeccionesModel", "ConfiguracionSecciones")
                        .WithMany("BancoPreguntas")
                        .HasForeignKey("ConfiguracionSeccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionSeccionesModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionTestModel", "ConfiguracionTest")
                        .WithMany("ConfiguracionesSecciones")
                        .HasForeignKey("ConfiguracionTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.TipoSeccionesModel", "TipoSecciones")
                        .WithMany("ConfiguracionesSecciones")
                        .HasForeignKey("TipoSeccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionTest");

                    b.Navigation("TipoSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionTestModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.EvaluadorModel", "Evaluador")
                        .WithMany("ConfiguracionesTest")
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.TipoTestModel", "TipoTest")
                        .WithMany()
                        .HasForeignKey("TipoTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluador");

                    b.Navigation("TipoTest");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.PacienteModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.CiudadModel", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ProvinciaModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.PaisModel", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionTestModel", "ConfiguracionTest")
                        .WithMany()
                        .HasForeignKey("IdConfiguracionTest")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.EvaluadorModel", "Evaluador")
                        .WithMany()
                        .HasForeignKey("IdEvaluador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.PacienteModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionTest");

                    b.Navigation("Evaluador");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestPreguntasModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionPreguntasModel", "ConfiguracionBancoPreguntas")
                        .WithMany()
                        .HasForeignKey("ConfiguracionBancoPreguntasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.TestSeccionesModel", "TestSecciones")
                        .WithMany("Preguntas")
                        .HasForeignKey("TestSeccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionBancoPreguntas");

                    b.Navigation("TestSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestSeccionesModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.ConfiguracionSeccionesModel", "ConfiguracionSecciones")
                        .WithMany()
                        .HasForeignKey("ConfiguracionSeccionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APITestPyscoIA.Models.Entidades.TestModel", "Test")
                        .WithMany("Secciones")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfiguracionSecciones");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TipoSeccionesModel", b =>
                {
                    b.HasOne("APITestPyscoIA.Models.Entidades.TipoTestModel", "TipoTest")
                        .WithMany("Secciones")
                        .HasForeignKey("TipoTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTest");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionPreguntasModel", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionSeccionesModel", b =>
                {
                    b.Navigation("BancoPreguntas");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ConfiguracionTestModel", b =>
                {
                    b.Navigation("ConfiguracionesSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.EvaluadorModel", b =>
                {
                    b.Navigation("ConfiguracionesTest");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.PaisModel", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.ProvinciaModel", b =>
                {
                    b.Navigation("Ciudades");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestModel", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TestSeccionesModel", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TipoSeccionesModel", b =>
                {
                    b.Navigation("ConfiguracionesSecciones");
                });

            modelBuilder.Entity("APITestPyscoIA.Models.Entidades.TipoTestModel", b =>
                {
                    b.Navigation("Secciones");
                });
#pragma warning restore 612, 618
        }
    }
}
